### PR TITLE
InstantOS support

### PR DESCRIPTION
**Pull request by Titaniumtown**
I am basing this off of the arch linux install script. I still have some issues to fix, but expect support soon!

### CODE REVIEW

**Comment by Titaniumtown** [comment]
I'm getting an issue, i don't know what's causing it: 

`[10/19 ( 52%)] Downloading bootstrap packages
[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] 100%
ERROR: Unexpected error occurred.
If you let brl-fetch automatically choose a mirror, it may have chosen a bad one.  Try manually providing a mirror with --mirror`

**Comment by Titaniumtown** [comment]
It seems like this distro is actually manjaro based, so I'll change this fetch script to reflect that.

**Comment by Titaniumtown** [comment]
Figured out the issue, something to do with checksums and the like.

**Comment by paradigm** [comment]
While I don't think it's documented anywhere, we don't currently allow using one distro's mirrors to fetch another distro.  The main concern here is the possibility that one distro's mirror would be upset we're using its bandwidth for another distro's purposes, and I don't want to risk it.  Using Arch's mirror for Arch things seems reasonable, but using Arch's mirror for InstantOS things might make someone upset.

I know this rules out distros whose files are supersets of other distros, like Mint is to Debian.  We don't have a firm policy to handle this at this point in time.  We might loosen this `brl fetch` restriction later, or we might make a different tool to automate converting a "base" distro into a superset one; not sure yet.

Historically there hasn't been much interest amongst Bedrock folks to combine parts of multiple superset distros.  Given this, most people just hijack the one superset distro they're interested in and `brl fetch` whatever else they want.  There isn't much pressing need for `brl fetch` support of superset distros.

**Comment by Titaniumtown** [comment]
ok, so should this pr just be closed then?

**Comment by paradigm** [comment]
I don't see a preferable alternative.

**Pull request closed without merging**
