### PR TITLE
Add paru support script

### PR DESCRIPTION
**Pull request by NICHOLAS85**
No changes from yay script were necessary besides yay -> paru rename.

### CODE REVIEW

**Comment by NICHOLAS85** [comment]
I've identified a difference in behavior from paru compared to yay. I'm going to close this until I've had time to check all implementations.

**Comment by NICHOLAS85** [comment]
For now the only problematic difference I found was updating the package database. Paru expects a target package for reinstallation, I've simply hidden this error message. Some operations can be simplified with new flags however I found some of these flags haven't been implemented yet or aren't working correctly. For now I'll keep an eye on development and update as necessary.

**Comment by NICHOLAS85** [comment]
Noting for future reference: Paru provides a remove orphans function via the `-c/--clean` flag. Once a bugfix I'm tracking is included in a release I'll update `user_interfaces` and `implimentations`

**Comment by NICHOLAS85** [comment]
Fixes I've been tracking have been included in latest release meaning this PR is ready to be accepted

**Comment by NICHOLAS85** [comment]
If the auto_escalate pr gets accepted I'll update this to reflect the needed changes.

**Review by Pan00Pernicek — APPROVED** [review]
works properly for me

**Comment by paradigm** [comment]
Looks good to me!

**Pull request merged**
